### ISSUE TITLE
Neptune Staff Freeze Crash

### ISSUE THREAD

**Issue by mkozuma** [grim3212/grim-pack#104] opened 2017-10-30 05:43 UTC
###### Forge Version:  1.12.2-forge1.12.2-14.23.0.2491
------
When I try to freeze a mob, my minecraft crashes with the following error message, "The game crashed whilst rendering entity in world
Error: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: layerRenderers." I am doing this in a singleplayer superflat world using the following other mods: Advanced Swords, Biomes o Plenty (not in a BOP world though), Voidcraft, Just Enough Items, More Commands, OptiFine HD, and Tam Modized.

**Comment by grim3212** [comment] 2017-10-30 16:07
Duplicate of #102

**Closed as completed by grim3212** 2017-10-30 16:07 UTC
Labels: duplicate
