### ISSUE TITLE
Pokeball Inventory Loss After Capturing a Minecolonies Citizen

### ISSUE THREAD

**Issue by WenXin20** [grim3212/grim-pack#75] opened 2017-02-13 02:24 UTC
1.10.2-Forge 2221
[Minecolonies v0.6 solid](https://minecraft.curseforge.com/projects/minecolonies)
After I captured a Minecolonies villager using the poke ball and then placed him back down, the villager is teleported to its home point instead of the spot it was placed at and the villagers inventory is cleared.

**Comment by grim3212** [comment] 2017-02-16 20:14
Not sure if I will be able to fix this with out a special case for Minecolony villagers. It seems that you can't just set their position. It always goes back to their home location. I'll look into it but I am not sure.

**Comment by WenXin20** [comment] 2017-02-16 20:42
Ok, thanks. I'll open an issue on their side too. 
It seems to happen with other mob capturing items from other mods as well.

**Comment by grim3212** [comment] 2017-12-12 20:34
Closing as the devs said it was intended.

**Closed as completed by grim3212** 2017-12-12 20:34 UTC
Labels: bug, mod compat
