### ISSUE TITLE
Crash when break Cheese maker (1.11.2)(Grim Pack-1.11.2-4.0.1.20)

### ISSUE THREAD

**Issue by BuckTheWeasel** [grim3212/grim-pack#95] opened 2017-08-12 12:02 UTC
Crash when break Cheese maker on Creative
 (i put the milk in and break the cheesmaker and it will crash)
https://pastebin.com/iG4BMJ9S

**Comment by grim3212** [comment] 2017-08-12 17:31
I'm having problems reproducing this. Does this happen to you even without FoamFix or are you doing anything special to make this happen besides just putting milk in and breaking it?

**Comment by grim3212** [comment] 2017-12-12 20:40
Closing this because I am unable to reproduce and no other information was given. Tell me if anyone is still experiencing this.

**Closed as completed by grim3212** 2017-12-12 20:40 UTC
Labels: bug, needs testing
